// Writes seed.sql containing one UNREGISTERED row per designation.
// Usage: node scripts/generate-seed.mjs [count]
import { writeFileSync } from 'node:fs';

const count = parseInt(process.argv[2] || '100', 10);
if (!Number.isInteger(count) || count < 1 || count > 9999) {
  console.error('count must be 1..9999');
  process.exit(1);
}

const rows = [];
for (let n = 1; n <= count; n++) {
  rows.push(`('${String(n).padStart(4, '0')}', ${n})`);
}

const sql = `-- Generated by scripts/generate-seed.mjs -- do not edit by hand.
-- Re-running is safe: existing rows are left untouched.
INSERT OR IGNORE INTO records (id, n) VALUES
${rows.join(',\n')};
`;

writeFileSync('seed.sql', sql);
console.log(`seed.sql written: ${count} designations (0001..${String(count).padStart(4, '0')})`);
