// Makes one secret per designation, writes the tag URLs and the SQL that
// teaches the database their hashes.
//
// RE-RUNNING THIS INVALIDATES EVERY TAG YOU HAVE ALREADY PROGRAMMED.
// Run it once, program from the csv it writes, and keep that csv.
import { writeFileSync, existsSync } from 'node:fs';
import { randomBytes, createHash } from 'node:crypto';

const base = (process.argv[2] || '').replace(/\/+$/, '');
const count = parseInt(process.argv[3] || '100', 10);

if (!/^https:\/\/[^\s/]+$/.test(base)) {
  console.error('usage: node scripts/generate-keys.mjs https://your-site.pages.dev [count]');
  process.exit(1);
}

if (existsSync('urls.csv') && !process.argv.includes('--force')) {
  console.error('urls.csv already exists. Re-running makes new keys and every');
  console.error('tag already written stops working. Pass --force if you mean it.');
  process.exit(1);
}

// no 0/O/1/I/L: these get typed off a card in a dark room
const ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

function key() {
  const bytes = randomBytes(8);
  let out = '';
  for (const b of bytes) out += ALPHABET[b % ALPHABET.length];
  return out;
}

const sha = (s) => createHash('sha256').update(s).digest('hex');

const rows = ['designation,key,url'];
const sql = ['-- generated by scripts/generate-keys.mjs'];

for (let n = 1; n <= count; n++) {
  const id = String(n).padStart(4, '0');
  const k = key();
  rows.push(`FPE-${id},${k},${base}/f/${id}?k=${k}`);
  sql.push(`UPDATE records SET claim_key_hash = '${sha(k)}' WHERE id = '${id}';`);
}

writeFileSync('urls.csv', rows.join('\n') + '\n');
writeFileSync('keys.sql', sql.join('\n') + '\n');

console.log(`urls.csv  ${count} tags, keys included -- this is the file you program from`);
console.log('keys.sql  load it with:');
console.log('          npx wrangler d1 execute fpe --remote --file=./keys.sql');
console.log('');
console.log('Keep urls.csv. It is the only copy of the keys.');
